# Generated by Django 6.0.1 on 2026-06-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosMachine',
        ),
    ]
