# Generated by Django 6.0.1 on 2026-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valabilitate_zile', models.IntegerField(default=90)),
            ],
            options={
                'verbose_name': 'Produs',
                'verbose_name_plural': 'Produse',
                'db_table': 'produse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locatie_pos', models.CharField(default='Locatie', max_length=100)),
                ('serie', models.CharField(default='PNBO', max_length=50)),
                ('numar', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Serii',
                'db_table': 'serii',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketMachine',
            fields=[
                ('pos_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('last_offline', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('failure_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ticket Machine',
                'verbose_name_plural': 'Ticket Machines',
                'db_table': 'ticket_machines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tranzactie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produs', models.IntegerField()),
                ('cantitate', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_tranzactie', models.DateTimeField()),
                ('pos_id', models.IntegerField()),
                ('nr', models.BigIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Tranzactie',
                'verbose_name_plural': 'Tranzactii',
                'db_table': 'tranzactii',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('parola', models.CharField(max_length=32)),
                ('tip', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'User Legacy',
                'verbose_name_plural': 'Useri Legacy',
                'db_table': 'useri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PosPaper',
            fields=[
                ('pos_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tickets_at_last_change', models.IntegerField()),
                ('roll_capacity', models.IntegerField(default=1000)),
                ('last_change', models.DateTimeField()),
            ],
            options={
                'db_table': 'pos_paper',
                'managed': True,
            },
        ),
    ]
