# Generated by Django 6.0.1 on 2026-01-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valabilitate_zile', models.IntegerField(default=90)),
            ],
            options={
                'db_table': 'produse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='PNBO', max_length=50)),
                ('numar', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'serii',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tranzactie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produs', models.IntegerField()),
                ('cantitate', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_tranzactie', models.DateTimeField()),
                ('pos_id', models.IntegerField()),
                ('nr', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'tranzactii',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('parola', models.CharField(max_length=32)),
                ('tip', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'useri',
                'managed': False,
            },
        ),
    ]
