# Generated by Django 6.0.1 on 2026-01-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPaper',
            fields=[
                ('pos_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tickets_at_last_change', models.IntegerField()),
                ('roll_capacity', models.IntegerField(default=1000)),
                ('last_change', models.DateTimeField()),
            ],
            options={
                'db_table': 'pos_paper',
                'managed': False,
            },
        ),
    ]
