# Generated by Django 6.0.1 on 2026-01-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_pospaper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produs',
            options={'managed': False, 'verbose_name': 'Produs', 'verbose_name_plural': 'Produse'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'managed': False, 'verbose_name': 'Serie', 'verbose_name_plural': 'Serii'},
        ),
        migrations.AlterModelOptions(
            name='tranzactie',
            options={'managed': False, 'verbose_name': 'Tranzactie', 'verbose_name_plural': 'Tranzactii'},
        ),
        migrations.AlterModelOptions(
            name='userlegacy',
            options={'managed': False, 'verbose_name': 'User Legacy', 'verbose_name_plural': 'Useri Legacy'},
        ),
    ]
