# Generated by Django 6.0.1 on 2026-02-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_alter_produs_options_alter_serie_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMachine',
            fields=[
                ('pos_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('last_offline', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('failure_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ticket Machine',
                'verbose_name_plural': 'Ticket Machines',
                'db_table': 'ticket_machines',
                'managed': False,
            },
        ),
    ]
